version: "3.7"
services:
  postgres:
    image: postgres:11
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=products
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    ports:
      - "9000:80"
    command: >
        /bin/sh -c "
          while ! nc -z -w1 postgres 5432;
          do
            echo sleeping;
            sleep 1;
          done;
          while ! nc -z -w1 api 80;
          do
            echo sleeping;
            sleep 1;
          done;
          echo Started!;
        "