version: "3.7"
services:
  api:
    build:
      context: .
    ports:
      - "9000:80"
    command: >
        /bin/sh -c "
          while ! nc -z -w1 api 80;
          do
            echo sleeping;
            sleep 1;
          done;
          echo Started!;
        "